services:
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    restart: always
    ports:
      - "9000:9000"
    networks:
      - sonar_net
    environment:
      # Local database credentials for sonar connection
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonarqube_local_db
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonarpass
    volumes:
      # Sonarqube local data persistence volume
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: sonarqube-db
    restart: always
    environment:
      # Local database credentials
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonarpass
      - POSTGRES_DB=sonarqube_local_db
    volumes:
      # PostgreSQL data persistence volume
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - sonar_net

networks:
  sonar_net:
    driver: bridge

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql_data:
